/home/ubuntu/Documents/source/callback-verification/cbverifier/driver.py:71: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  e.message))
Traceback (most recent call last):
  File "/home/ubuntu/Documents/source/callback-verification/cbverifier/driver.py", line 502, in <module>
    main()
  File "/home/ubuntu/Documents/source/callback-verification/cbverifier/driver.py", line 409, in main
    driver = Driver(driver_opts)
  File "/home/ubuntu/Documents/source/callback-verification/cbverifier/driver.py", line 71, in __init__
    e.message))
Exception: An error happened reading the trace in /home/ubuntu/Documents/data/monkey_traces/alert-dialog-traces-1/_traces/long0122-jqmMobileDemo-jqmMobileDemo/monkeyTraces/trace-MainActivity-debug_2017-04-15_21:58:46.repaired ()
real 1.36
user 1.14
sys 0.10
