/home/s/Documents/source/callback-verification/cbverifier/driver.py:66: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  e.message))
Traceback (most recent call last):
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 466, in <module>
    main()
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 390, in main
    driver = Driver(driver_opts)
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 66, in __init__
    e.message))
Exception: An error happened reading the trace in /home/ubuntu/Documents/data/monkey_traces/other-dialog-traces-2/_traces/ROGUE-JCTD-Arbiter-Android-Arbiter-Android/monkeyTraces/trace-Arbiter-debug-unaligned_2017-04-16_13:24:22.repaired (Wrong integer value in message!)
real 1.02
user 0.93
sys 0.06
