/home/s/Documents/source/callback-verification/cbverifier/driver.py:66: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  e.message))
Traceback (most recent call last):
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 466, in <module>
    main()
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 390, in main
    driver = Driver(driver_opts)
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 66, in __init__
    e.message))
Exception: An error happened reading the trace in /home/ubuntu/Documents/data/monkey_traces/frag-act-last-batch-2/_traces/hahnjo-SMBProvider-main/monkeyTraces/trace-a99ce17cff57653062b04280af28f61055af2efc-debug_2017-04-17_03:00:19.repaired (pop from empty list)
real 0.93
user 0.83
sys 0.07
