/home/s/Documents/source/callback-verification/cbverifier/driver.py:66: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  e.message))
Traceback (most recent call last):
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 466, in <module>
    main()
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 390, in main
    driver = Driver(driver_opts)
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 66, in __init__
    e.message))
Exception: An error happened reading the trace in /home/ubuntu/Documents/data/monkey_traces/alert-dialog-traces-1/_traces/long0122-jqmMobileDemo-jqmMobileDemo/monkeyTraces/trace-MainActivity-debug-unaligned_2017-04-15_21:36:28.repaired ()
real 0.75
user 0.68
sys 0.04
