/home/s/Documents/source/callback-verification/cbverifier/driver.py:66: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  e.message))
Traceback (most recent call last):
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 466, in <module>
    main()
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 390, in main
    driver = Driver(driver_opts)
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 66, in __init__
    e.message))
Exception: An error happened reading the trace in /home/ubuntu/Documents/data/monkey_traces/frag-act-last-batch/_traces/codebutler-farebot-main/monkeyTraces/trace-2f08cb3fa361e5e35dcbf2868892183ef409264d-debug_2017-04-16_21:59:36.repaired ()
real 3.77
user 3.40
sys 0.33
