/home/s/Documents/source/callback-verification/cbverifier/driver.py:66: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  e.message))
Traceback (most recent call last):
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 466, in <module>
    main()
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 390, in main
    driver = Driver(driver_opts)
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 66, in __init__
    e.message))
Exception: An error happened reading the trace in /home/ubuntu/Documents/data/monkey_traces/frag-act-last-batch/_traces/codlab-android_internal_external-program/monkeyTraces/trace-Internal2External_2017-04-17_02:53:48.repaired (pop from empty list)
real 0.77
user 0.67
sys 0.08
