/home/s/Documents/source/callback-verification/cbverifier/driver.py:66: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  e.message))
Traceback (most recent call last):
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 466, in <module>
    main()
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 390, in main
    driver = Driver(driver_opts)
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 66, in __init__
    e.message))
Exception: An error happened reading the trace in /home/ubuntu/Documents/data/monkey_traces/frag-act-last-batch/_traces/smarek-Simple-Dilbert-main/monkeyTraces/trace-9009414f0b2b688712b2a7e546ab4943ff8fc334-debug-unaligned_2017-04-17_07:02:51.repaired (pop from empty list)
real 3.52
user 3.23
sys 0.26
