/home/s/Documents/source/callback-verification/cbverifier/driver.py:65: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  e.message))
Traceback (most recent call last):
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 448, in <module>
    main()
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 377, in main
    driver = Driver(driver_opts)
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 65, in __init__
    e.message))
Exception: An error happened reading the trace in /home/ubuntu/Documents/data/monkey_traces/smblott-github-intent_radio-bin/monkeyTraces/trace_2017-04-07_14:40:35.repaired ()
real 0.52
user 0.46
sys 0.02
