/home/s/Documents/source/callback-verification/cbverifier/driver.py:65: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  e.message))
Traceback (most recent call last):
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 448, in <module>
    main()
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 377, in main
    driver = Driver(driver_opts)
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 65, in __init__
    e.message))
Exception: An error happened reading the trace in /home/ubuntu/Documents/data/monkey_traces/bparmentier-OpenBikeSharing-app/monkeyTraces/trace-app-debug_2017-04-26_18:40:46.repaired ()
real 2.55
user 2.32
sys 0.20
