/home/ubuntu/Documents/source/callback-verification/cbverifier/driver.py:71: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  e.message))
Traceback (most recent call last):
  File "/home/ubuntu/Documents/source/callback-verification/cbverifier/driver.py", line 502, in <module>
    main()
  File "/home/ubuntu/Documents/source/callback-verification/cbverifier/driver.py", line 409, in main
    driver = Driver(driver_opts)
  File "/home/ubuntu/Documents/source/callback-verification/cbverifier/driver.py", line 71, in __init__
    e.message))
Exception: An error happened reading the trace in /home/ubuntu/Documents/data/monkey_traces/other-dialog-traces-1/_traces/M0nk3yofdoom-Moodle-for-Android-bin/monkeyTraces/trace-Login-debug-unaligned_2017-04-16_07:42:05.repaired (pop from empty list)
real 0.75
user 0.63
sys 0.07
