/home/s/Documents/source/callback-verification/cbverifier/driver.py:66: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  e.message))
Traceback (most recent call last):
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 466, in <module>
    main()
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 390, in main
    driver = Driver(driver_opts)
  File "/home/s/Documents/source/callback-verification/cbverifier/driver.py", line 66, in __init__
    e.message))
Exception: An error happened reading the trace in /home/ubuntu/Documents/data/monkey_traces/_traces/hahnjo-SMBProvider-main/monkeyTraces/trace-6cd9987a370debd5a94768b943bef76e01cd4279-debug_2017-04-25_23:20:29.repaired (pop from empty list)
real 0.98
user 0.89
sys 0.06
