/home/ubuntu/Documents/source/callback-verification/cbverifier/driver.py:71: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  e.message))
Traceback (most recent call last):
  File "/home/ubuntu/Documents/source/callback-verification/cbverifier/driver.py", line 502, in <module>
    main()
  File "/home/ubuntu/Documents/source/callback-verification/cbverifier/driver.py", line 409, in main
    driver = Driver(driver_opts)
  File "/home/ubuntu/Documents/source/callback-verification/cbverifier/driver.py", line 71, in __init__
    e.message))
Exception: An error happened reading the trace in /home/ubuntu/Documents/data/monkey_traces/output/dogtim-VideoEditor-bin/monkeyTraces/trace_2017-04-07_17:26:14.repaired (pop from empty list)
real 0.34
user 0.26
sys 0.04
