/home/ubuntu/Documents/source/callback-verification/cbverifier/driver.py:71: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  e.message))
Traceback (most recent call last):
  File "/home/ubuntu/Documents/source/callback-verification/cbverifier/driver.py", line 502, in <module>
    main()
  File "/home/ubuntu/Documents/source/callback-verification/cbverifier/driver.py", line 409, in main
    driver = Driver(driver_opts)
  File "/home/ubuntu/Documents/source/callback-verification/cbverifier/driver.py", line 71, in __init__
    e.message))
Exception: An error happened reading the trace in /home/ubuntu/Documents/data/monkey_traces/fragment-startActivity-traces-2/_traces/infinum-android_dbinspector-ExampleApp/monkeyTraces/trace-ExampleApp-debug_2017-04-16_00:51:59.repaired (pop from empty list)
real 1.12
user 0.97
sys 0.12
